spring:
  config:
    import: optional:file:./.env[.properties]

server:
  port: 8082

payriff:
  secret-key: ${PAYRIFF_SECRET_KEY:880F3C1401C240F78762E93CCBD17039}
  base-url: https://api.payriff.com/api/v3

public:
  domain: https://sackclothed-marlana-nongeological.ngrok-free.dev